# Generated by Django 5.0.6 on 2024-05-28 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chocolux', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='application',
            options={'verbose_name': 'Заявка', 'verbose_name_plural': 'Заявки'},
        ),
        migrations.AddField(
            model_name='products',
            name='description',
            field=models.TextField(default='Empty', verbose_name='Описание'),
        ),
    ]
